# Generated by Django 3.2.6 on 2021-09-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myToDo', '0002_auto_20210904_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='updated_date',
            new_name='update_date',
        ),
    ]
