# Generated by Django 3.2.6 on 2021-09-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myToDo', '0003_rename_updated_date_todo_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='text_todo',
        ),
    ]
